---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: xenial
    image: ubuntu:16.04
  - name: bionic
    image: ubuntu:18.04
  - name: focal
    image: ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: testinfra
